"use client";

import { useEffect, useState } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import { Bell, Check, ChevronLeft, ChevronRight, Database, Download, Eye, EyeOff, FileClock, KeyRound, Languages, Link2, LockKeyhole, Plus, Save, Settings2, ShieldCheck, Trash2, UserRound, Users, Webhook, X } from "lucide-react";
import { Badge } from "@minsaj/ui";
import type { Locale } from "@minsaj/contracts";
import { DemoToast } from "@/components/domain/operations/shared";

import { ScrollFx } from "@/components/universal/scroll-fx";
type SettingsSection = "profile" | "preferences" | "workspace" | "providers" | "integrations" | "data" | "audit";

/* W-DS Phase 2 (HIE-02): settings rebuilt on the mj-* primitives.
   Anatomy: settings-layout → mj-section → (mj-surface | mj-data-list).
   A list is never nested inside a surface (R-SURF-1); rows carry data-label
   for the ≤640px labelled-card collapse (layout.css §8). */

function SettingToggle({ checked, onChange, label, detail }: { checked: boolean; onChange: (checked: boolean) => void; label: string; detail: string }) {
  return <label className="settings-row"><span><strong>{label}</strong><small>{detail}</small></span><input className="switch-input" type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /><span className="switch-visual" aria-hidden="true"><span /></span></label>;
}

export function SettingsPrototype({ locale }: { locale: Locale }) {
  const ar = locale === "ar";
  const [section, setSection] = useState<SettingsSection>("profile");
  const [notice, setNotice] = useState("");
  const [providerOpen, setProviderOpen] = useState(false);
  const [provider, setProvider] = useState("Northstar");
  const [keyValue, setKeyValue] = useState("");
  const [showKey, setShowKey] = useState(false);
  const [credentialAdded, setCredentialAdded] = useState(false);
  const [weeklyDigest, setWeeklyDigest] = useState(true);
  const [approvalAlerts, setApprovalAlerts] = useState(true);
  const [denseMode, setDenseMode] = useState(false);
  const DirectionIcon = ar ? ChevronLeft : ChevronRight;
  useEffect(() => { if (!notice) return; const timer = window.setTimeout(() => setNotice(""), 2800); return () => window.clearTimeout(timer); }, [notice]);
  const sections: Array<[SettingsSection, string, string, typeof UserRound]> = [
    ["profile", ar ? "الملف الشخصي" : "Profile", ar ? "الاسم والحساب" : "Name and account", UserRound],
    ["preferences", ar ? "التفضيلات" : "Preferences", ar ? "اللغة والكثافة والتنبيهات" : "Language, density, alerts", Languages],
    ["workspace", ar ? "مساحة العمل" : "Workspace", ar ? "الاسم والسياسات" : "Name and policies", Users],
    ["providers", ar ? "مفاتيح المزودين" : "Provider keys", ar ? "BYOK آمن ومحدود" : "Safe, scoped BYOK", KeyRound],
    ["integrations", ar ? "التكاملات" : "Integrations", ar ? "اتصالات خارجية" : "External connections", Link2],
    ["data", ar ? "البيانات والخصوصية" : "Data and privacy", ar ? "التصدير والاحتفاظ" : "Export and retention", Database],
    ["audit", ar ? "سجل التدقيق" : "Audit log", ar ? "أحداث السلطة" : "Authority events", FileClock],
  ];
  const integrations: Array<{ name: string; detail: string; connected: boolean; icon: typeof Bell }> = [
    { name: "Slack", detail: ar ? "إشعارات الفريق وطلبات الموافقة" : "Team alerts and approval requests", connected: true, icon: Webhook },
    { name: "Google Drive", detail: ar ? "قراءة ملفات ضمن مجلدات محددة" : "Read files from selected folders", connected: true, icon: Database },
    { name: "Email", detail: ar ? "إرسال ملخصات بعد موافقة بشرية" : "Send digests after human approval", connected: false, icon: Bell },
  ];
  const policies: Array<{ icon: typeof ShieldCheck; title: string; body: string; badge: string }> = [
    { icon: ShieldCheck, title: ar ? "الموافقة قبل الأثر الخارجي" : "Approval before external impact", body: ar ? "افتراضي إلزامي لكل وكيل وتدفق جديد." : "Mandatory default for every new agent and flow.", badge: ar ? "إلزامي" : "Required" },
    { icon: KeyRound, title: ar ? "عدم التحول التلقائي بين الدافعين" : "No automatic payer switching", body: ar ? "تعطل BYOK لا يحول التشغيل إلى الرصيد دون سياسة صريحة." : "A BYOK failure never switches to credits without explicit policy.", badge: ar ? "محمي" : "Protected" },
    { icon: LockKeyhole, title: ar ? "أقل صلاحية للمصادر" : "Least privilege for sources", body: ar ? "الوكلاء الجديدة لا ترى مجموعات معرفة حتى تُربط صراحة." : "New agents see no knowledge collections until explicitly linked.", badge: ar ? "محمي" : "Protected" },
  ];
  const dataActions: Array<{ icon: typeof Download; title: string; body: string; cta: string; danger?: boolean; onClick?: () => void }> = [
    { icon: Download, title: ar ? "تصدير بيانات المساحة" : "Export workspace data", body: ar ? "المشاريع والمحادثات والتعريفات وسجلات القرارات بصيغة محمولة." : "Projects, conversations, definitions, and decision logs in portable formats.", cta: ar ? "طلب تصدير" : "Request export", onClick: () => setNotice(ar ? "أُنشئ طلب تصدير تجريبي." : "A demo export request was created.") },
    { icon: FileClock, title: ar ? "سياسة الاحتفاظ" : "Retention policy", body: ar ? "سجلات التشغيل ٣٦٥ يومًا؛ المخرجات حسب المشروع." : "Run records for 365 days; artifacts follow project policy.", cta: ar ? "تعديل" : "Edit" },
    { icon: Trash2, title: ar ? "حذف مساحة العمل" : "Delete workspace", body: ar ? "يتطلب تأكيدًا كتابيًا وإعادة مصادقة ونقل الموارد اللازمة." : "Requires typed confirmation, re-authentication, and required resource transfer.", cta: ar ? "مراجعة الأثر" : "Review impact", danger: true },
  ];
  const auditEvents: Array<[string, string, string, string]> = [
    ["09:42:18", ar ? "وافقت سارة على إرسال ملخص الرصد" : "Sarah approved sending the monitoring digest", "approval.approved", "run_weekly_watch"],
    ["09:31:04", ar ? "غيّر يوسف دور مايا إلى منشئ" : "Yousef changed Maya’s role to Builder", "member.role_changed", "mem_maya"],
    ["08:55:40", ar ? "تم التحقق من مفتاح Northstar" : "Northstar key was verified", "credential.verified", "cred_ns_01"],
    ["أمس", ar ? "نُشر الإصدار ٦ من تدفق الرصد" : "Weekly watch flow version 6 published", "flow.published", "flw_weekly_watch"],
  ];
  function saved(message: string) { setNotice(message); }

  const head = (title: string, desc: string) => <div className="mj-section__head"><div className="mj-section__head-copy"><h2 className="mj-section__title">{title}</h2><p className="mj-section__desc">{desc}</p></div></div>;

  return <div className="ops-page settings-page">
    <ScrollFx /><header className="page-header"><div className="page-header__copy"><p className="page-eyebrow">{ar ? "سياسات المساحة" : "Workspace policy"}</p><h1 className="page-title">{ar ? "الإعدادات" : "Settings"}</h1><p className="page-description">{ar ? "اضبط الحساب والسياسات والمزودين والخصوصية دون إخفاء الأثر أو الصلاحية المطلوبة." : "Configure account, policy, providers, and privacy without hiding impact or required authority."}</p></div></header><div className="settings-layout"><aside className="settings-nav mj-surface"><p>{ar ? "إعدادات فريق أفق" : "Horizon Team settings"}</p><nav aria-label={ar ? "أقسام الإعدادات" : "Settings sections"}>{sections.map(([id, label, detail, Icon]) => <button key={id} type="button" className={section === id ? "is-active" : ""} aria-current={section === id ? "page" : undefined} onClick={() => setSection(id)}><Icon size={16} /><span><strong>{label}</strong><small>{detail}</small></span><DirectionIcon size={14} /></button>)}</nav></aside><main className="settings-content">
    {section === "profile" ? <section className="mj-section">{head(ar ? "الملف الشخصي" : "Profile", ar ? "الهوية التي تظهر في القرارات وسجلات التدقيق." : "The identity shown in decisions and audit records.")}<div className="mj-surface"><div className="profile-settings-grid"><div className="profile-photo"><span>س</span><button className="button button--outline button--compact" type="button">{ar ? "تغيير الصورة" : "Change photo"}</button><small>{ar ? "PNG أو JPG · حتى ٢ م.ب" : "PNG or JPG · up to 2 MB"}</small></div><div><label className="field"><span>{ar ? "الاسم الظاهر" : "Display name"}</span><input defaultValue={ar ? "سارة الحربي" : "Sarah Alharbi"} /></label><label className="field"><span>{ar ? "البريد" : "Email"}</span><input value="sarah@minsaj.demo" readOnly /></label><label className="field"><span>{ar ? "المسمى" : "Job title"}</span><input defaultValue={ar ? "قائدة عمليات" : "Operations lead"} /></label></div></div><div className="settings-save-row"><span>{ar ? "تظهر التغييرات في القرارات اللاحقة فقط." : "Changes appear in future decisions only."}</span><button className="button button--primary button--default" type="button" onClick={() => saved(ar ? "حُفظ الملف الشخصي محليًا." : "Profile saved locally.")}><Save size={14} />{ar ? "حفظ التغييرات" : "Save changes"}</button></div></div></section> : null}
    {section === "preferences" ? <section className="mj-section">{head(ar ? "التفضيلات" : "Preferences", ar ? "لغة الواجهة وكثافتها وطريقة وصول التنبيهات." : "Interface language, density, and notification delivery.")}<div className="mj-surface"><div className="settings-group"><h3>{ar ? "الواجهة" : "Interface"}</h3><div className="settings-rows"><div className="settings-row"><span><strong>{ar ? "اللغة الأساسية" : "Primary language"}</strong><small>{ar ? "يمكن التبديل من الشريط العلوي دائمًا." : "You can always switch from the top bar."}</small></span><select defaultValue={locale}><option value="ar">العربية</option><option value="en">English</option></select></div><SettingToggle checked={denseMode} onChange={setDenseMode} label={ar ? "كثافة عالية" : "Dense mode"} detail={ar ? "صفوف أقصر ومساحة أكبر للمحتوى التشغيلي." : "Shorter rows and more room for operational content."} /></div></div><div className="settings-group"><h3>{ar ? "الإشعارات" : "Notifications"}</h3><div className="settings-rows"><SettingToggle checked={approvalAlerts} onChange={setApprovalAlerts} label={ar ? "طلبات الموافقة" : "Approval requests"} detail={ar ? "تنبيه داخل المنتج عند توقف تشغيل ينتظر قرارك." : "In-product alert when a run pauses for your decision."} /><SettingToggle checked={weeklyDigest} onChange={setWeeklyDigest} label={ar ? "ملخص أسبوعي" : "Weekly digest"} detail={ar ? "نشاط المشاريع والتكلفة والتنبيهات المفتوحة." : "Project activity, cost, and open alerts."} /></div></div><div className="settings-save-row"><span>{ar ? "المعاينة تطبق التبديلات محليًا." : "The preview applies toggles locally."}</span><button className="button button--primary button--default" type="button" onClick={() => saved(ar ? "حُفظت التفضيلات محليًا." : "Preferences saved locally.")}><Save size={14} />{ar ? "حفظ التفضيلات" : "Save preferences"}</button></div></div></section> : null}
    {section === "workspace" ? <section className="mj-section">{head(ar ? "مساحة العمل" : "Workspace", ar ? "الاسم والافتراضيات التي تحكم الموارد الجديدة." : "Name and defaults governing new resources.")}<div className="mj-surface"><label className="field"><span>{ar ? "اسم المساحة" : "Workspace name"}</span><input defaultValue={ar ? "فريق أفق" : "Horizon Team"} /></label><div className="data-action-list">{policies.map(({ icon: Icon, title, body, badge }) => <article key={title}><span><Icon size={16} /></span><div><strong>{title}</strong><p>{body}</p></div><Badge tone="success">{badge}</Badge></article>)}</div><div className="settings-save-row"><span>{ar ? "يتطلب تغيير السياسات دور المسؤول." : "Policy changes require an admin role."}</span><button className="button button--primary button--default" type="button" onClick={() => saved(ar ? "حُفظت سياسة المساحة في المحاكاة." : "Workspace policy saved in the simulation.")}><Save size={14} />{ar ? "حفظ السياسة" : "Save policy"}</button></div></div></section> : null}
    {section === "providers" ? <section className="mj-section"><div className="mj-section__head"><div className="mj-section__head-copy"><h2 className="mj-section__title">{ar ? "مفاتيح المزودين — BYOK" : "Provider keys — BYOK"}</h2><p className="mj-section__desc">{ar ? "بيانات الاعتماد لا تُعرض مجددًا ولا تغيّر الدافع تلقائيًا." : "Credentials are never shown again and never change the payer automatically."}</p></div><div className="mj-section__aside"><button className="button button--primary button--default" type="button" onClick={() => setProviderOpen(true)}><Plus size={14} />{ar ? "إضافة مفتاح" : "Add key"}</button></div></div><div className="mj-data-list providers-data-list" role="table" aria-label={ar ? "مفاتيح المزودين" : "Provider keys"}><div className="mj-data-list__head" role="row"><span>{ar ? "المزود" : "Provider"}</span><span>{ar ? "المفتاح" : "Key"}</span><span>{ar ? "الحالة" : "Status"}</span><span /></div><div className="mj-data-list__row" role="row"><span className="ops-cell-id" data-label={ar ? "المزود" : "Provider"}><i>N</i><span><strong>Northstar API</strong><small>{ar ? "نطاق مساحة العمل · أضيف في ٥ سبتمبر" : "Workspace scope · added Sep 5"}</small></span></span><span className="masked-key mono" data-label={ar ? "المفتاح" : "Key"}>•••• •••• ns_42</span><span data-label={ar ? "الحالة" : "Status"}><Badge tone="success">{ar ? "متحقق" : "Verified"}</Badge></span><button className="icon-button" type="button" aria-label={ar ? "إجراءات Northstar" : "Northstar actions"}><Settings2 size={16} /></button></div>{credentialAdded ? <div className="mj-data-list__row" role="row"><span className="ops-cell-id" data-label={ar ? "المزود" : "Provider"}><i>{provider.slice(0, 1)}</i><span><strong>{provider} API</strong><small>{ar ? "نطاق مساحة العمل · أضيف الآن" : "Workspace scope · added now"}</small></span></span><span className="masked-key mono" data-label={ar ? "المفتاح" : "Key"}>•••• •••• demo</span><span data-label={ar ? "الحالة" : "Status"}><Badge tone="success">{ar ? "تجريبي" : "Demo"}</Badge></span><button className="icon-button" type="button" aria-label={ar ? `إجراءات ${provider}` : `${provider} actions`}><Settings2 size={16} /></button></div> : null}</div><div className="provider-safety-card"><ShieldCheck size={18} /><div><strong>{ar ? "سلوك المفتاح الآمن" : "Safe key behavior"}</strong><ul><li>{ar ? "لا يعاد المفتاح من API بعد الحفظ." : "The key is never returned by the API after saving."}</li><li>{ar ? "يُسجل النطاق والمزود وحالة الاختبار فقط." : "Only scope, provider, and test status are recorded."}</li><li>{ar ? "الإلغاء يمنع التشغيلات الجديدة فورًا." : "Revocation blocks new runs immediately."}</li></ul></div></div></section> : null}
    {section === "integrations" ? <section className="mj-section">{head(ar ? "التكاملات" : "Integrations", ar ? "الاتصالات التي قد تنشئ أثرًا خارج مساحة العمل." : "Connections that may create an effect outside the workspace.")}<div className="integration-grid">{integrations.map(({ name, detail, connected, icon: Icon }) => <article key={name}><span><Icon size={18} /></span><h3>{name}</h3><p>{detail}</p><Badge tone={connected ? "success" : "neutral"}>{connected ? (ar ? "متصل" : "Connected") : (ar ? "غير متصل" : "Not connected")}</Badge><button className="button button--outline button--compact" type="button">{connected ? (ar ? "إدارة" : "Manage") : (ar ? "مراجعة وتوصيل" : "Review and connect")}</button></article>)}</div><div className="provider-safety-card"><ShieldCheck size={18} /><div><strong>{ar ? "الأثر الخارجي خلف موافقة" : "External effects stay behind approval"}</strong><p>{ar ? "الاتصال وحده لا يمنح الوكلاء حق الإرسال؛ يلزم ربط الأداة وسياسة واضحة." : "Connecting alone does not let agents send; a tool link and explicit policy are still required."}</p></div></div></section> : null}
    {section === "data" ? <section className="mj-section">{head(ar ? "البيانات والخصوصية" : "Data and privacy", ar ? "الاحتفاظ والتصدير والحذف بأثر موضح قبل القرار." : "Retention, export, and deletion with impact shown before any decision.")}<div className="mj-surface"><div className="data-action-list">{dataActions.map(({ icon: Icon, title, body, cta, danger, onClick }) => <article key={title} className={danger ? "is-danger" : ""}><span><Icon size={18} /></span><div><strong>{title}</strong><p>{body}</p></div><button className={`button ${danger ? "button--quiet" : "button--outline"} button--compact`} type="button" onClick={onClick}>{cta}</button></article>)}</div></div></section> : null}
    {section === "audit" ? <section className="mj-section"><div className="mj-section__head"><div className="mj-section__head-copy"><h2 className="mj-section__title">{ar ? "سجل التدقيق" : "Audit log"}</h2><p className="mj-section__desc">{ar ? "قرارات السلطة والسياسات والمفاتيح والتغييرات الحساسة." : "Authority decisions, policies, keys, and sensitive changes."}</p></div><div className="mj-section__aside"><button className="button button--outline button--compact" type="button"><Download size={14} />CSV</button></div></div><div className="mj-data-list audit-data-list" role="table" aria-label={ar ? "سجل التدقيق" : "Audit log"}><div className="mj-data-list__head" role="row"><span>{ar ? "الوقت" : "Time"}</span><span /><span>{ar ? "الحدث" : "Event"}</span><span /></div>{auditEvents.map(([time, label, event, resource]) => <div className="mj-data-list__row" role="row" key={event}><span className="mono" data-label={ar ? "الوقت" : "Time"}>{time}</span><i className="audit-dot" aria-hidden="true" /><span data-label={ar ? "الحدث" : "Event"}><strong>{label}</strong><small className="mono">{event} · {resource}</small></span><button className="icon-button" type="button" aria-label={ar ? "عرض الحدث" : "View event"}><Eye size={14} /></button></div>)}</div></section> : null}
  </main></div><Dialog.Root open={providerOpen} onOpenChange={setProviderOpen}><Dialog.Portal><Dialog.Overlay className="command-overlay" /><Dialog.Content className="form-dialog provider-dialog" aria-describedby="provider-description"><div className="form-dialog__header"><div><Dialog.Title>{ar ? "إضافة مفتاح مزود" : "Add provider key"}</Dialog.Title><Dialog.Description id="provider-description">{ar ? "يُختبر المفتاح قبل حفظ metadata فقط. لن نعرض قيمته لاحقًا." : "The key is tested before saving metadata only. Its value will not be shown again."}</Dialog.Description></div><Dialog.Close asChild><button className="icon-button" type="button" aria-label={ar ? "إغلاق" : "Close"}><X size={16} /></button></Dialog.Close></div><label className="field"><span>{ar ? "المزود" : "Provider"}</span><select value={provider} onChange={(event) => setProvider(event.target.value)}><option>Northstar</option><option>Vertex Lane</option><option>Cedar Labs</option></select></label><label className="field"><span>{ar ? "مفتاح API" : "API key"}</span><div className="secret-input"><input type={showKey ? "text" : "password"} value={keyValue} onChange={(event) => setKeyValue(event.target.value)} placeholder="sk_demo_••••••••••" autoComplete="off" /><button className="icon-button" type="button" onClick={() => setShowKey((visible) => !visible)} aria-label={showKey ? (ar ? "إخفاء المفتاح" : "Hide key") : (ar ? "إظهار المفتاح" : "Show key")}>{showKey ? <EyeOff size={16} /> : <Eye size={16} />}</button></div></label><label className="field"><span>{ar ? "النطاق" : "Scope"}</span><select defaultValue="workspace"><option value="workspace">{ar ? "مساحة العمل" : "Workspace"}</option><option value="personal">{ar ? "شخصي" : "Personal"}</option></select></label><div className="provider-key-warning"><LockKeyhole size={16} /><p>{ar ? "هذه محاكاة فقط: القيمة لا تغادر المتصفح ولا تُرسل إلى مزود. لا تدخل مفتاحًا حقيقيًا." : "Simulation only: the value never leaves the browser or reaches a provider. Do not enter a real key."}</p></div><div className="form-dialog__actions"><Dialog.Close asChild><button className="button button--quiet button--default" type="button">{ar ? "إلغاء" : "Cancel"}</button></Dialog.Close><button className="button button--primary button--default" type="button" disabled={!keyValue.trim()} onClick={() => { setCredentialAdded(true); setProviderOpen(false); setKeyValue(""); setNotice(ar ? "أضيفت بيانات اعتماد تجريبية دون حفظ قيمة المفتاح." : "Demo credential metadata added without storing the key value."); }}><Check size={14} />{ar ? "اختبار وإضافة تجريبيًا" : "Test and add demo"}</button></div></Dialog.Content></Dialog.Portal></Dialog.Root>{notice ? <DemoToast message={notice} /> : null}</div>;
}
